// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Data;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TaskManager.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9850),
                            Description = "Познакомиться с основами ASP.NET Core MVC",
                            DueDate = new DateTime(2025, 12, 6, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9850),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Изучить ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 28, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9860),
                            Description = "Добавить Entity Framework и создать миграции",
                            DueDate = new DateTime(2025, 12, 2, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9850),
                            IsCompleted = true,
                            Priority = 1,
                            Title = "Настроить базу данных"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 27, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9860),
                            Description = "Разработать удобный пользовательский интерфейс",
                            DueDate = new DateTime(2025, 12, 13, 14, 45, 51, 8, DateTimeKind.Local).AddTicks(9860),
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Создать интерфейс"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
